# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Panel_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Panel_frame.sizePolicy().hasHeightForWidth())
        self.Panel_frame.setSizePolicy(sizePolicy)
        self.Panel_frame.setMaximumSize(QtCore.QSize(360, 16777215))
        self.Panel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Panel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Panel_frame.setObjectName("Panel_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Panel_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Progress_frame = QtWidgets.QFrame(self.Panel_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Progress_frame.sizePolicy().hasHeightForWidth())
        self.Progress_frame.setSizePolicy(sizePolicy)
        self.Progress_frame.setStyleSheet("background-color: rgb(255, 212, 0);")
        self.Progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Progress_frame.setObjectName("Progress_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Progress_frame)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.animation_progress_bar = QtWidgets.QProgressBar(self.Progress_frame)
        self.animation_progress_bar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color: rgb(122, 201, 67);\n"
"border : 1px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"     background-color: #157F1F;\n"
"     width: 20px;\n"
" }")
        self.animation_progress_bar.setProperty("value", 0)
        self.animation_progress_bar.setTextVisible(False)
        self.animation_progress_bar.setObjectName("animation_progress_bar")
        self.gridLayout.addWidget(self.animation_progress_bar, 2, 0, 1, 2)
        self.percent_label = QtWidgets.QLabel(self.Progress_frame)
        self.percent_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 20pt \"Moon\";\n"
"font-weight:bold;")
        self.percent_label.setObjectName("percent_label")
        self.gridLayout.addWidget(self.percent_label, 0, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.progress_label = QtWidgets.QLabel(self.Progress_frame)
        self.progress_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.progress_label.setObjectName("progress_label")
        self.gridLayout.addWidget(self.progress_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.Progress_frame, 0, QtCore.Qt.AlignTop)
        self.menu_frame = QtWidgets.QFrame(self.Panel_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_frame.sizePolicy().hasHeightForWidth())
        self.menu_frame.setSizePolicy(sizePolicy)
        self.menu_frame.setStyleSheet("background-color: rgb(240, 237, 238);")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab_btn = QtWidgets.QFrame(self.menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_btn.sizePolicy().hasHeightForWidth())
        self.tab_btn.setSizePolicy(sizePolicy)
        self.tab_btn.setStyleSheet("background-color: rgb(255, 212, 0);")
        self.tab_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tab_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tab_btn.setObjectName("tab_btn")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_btn)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.path_btn = QtWidgets.QPushButton(self.tab_btn)
        self.path_btn.setMinimumSize(QtCore.QSize(0, 70))
        self.path_btn.setStyleSheet("QPushButton{\n"
                                    "    color:#000000;\n"
                                    "    font: 75 16pt \"Moon\";\n"
                                    "    font-weight:bold;\n"
                                    "    background-color:#ebc400;\n"
                                    "    border-top: 5px solid #ebc400;\n"
                                    "    border-left: 5px solid #ebc400;\n"
                                    "    border-right: 5px solid #ebc400;\n"
                                    "    border-bottom: 5px solid #797270;\n"
                                    "    border-radius: 1px;\n"
                                    "}")
        self.path_btn.setObjectName("path_btn")
        self.horizontalLayout_8.addWidget(self.path_btn)
        self.option_btn = QtWidgets.QPushButton(self.tab_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_btn.sizePolicy().hasHeightForWidth())
        self.option_btn.setSizePolicy(sizePolicy)
        self.option_btn.setMinimumSize(QtCore.QSize(0, 70))
        self.option_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.option_btn.setStyleSheet("QPushButton{\n"
"    color:#000000;\n"
"    font: 75 16pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#ffd400;\n"
"    border: 5px solid #ffd400;\n"
"    border-radius: 1px;\n"
"\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    color:#000000;\n"
"    font: 75 16pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#ebc400;\n"
"    border-top: 5px solid #ebc400;\n"
"    border-left: 5px solid #ebc400;\n"
"    border-right: 5px solid #ebc400;\n"
"    border-bottom: 5px solid #797270;\n"
"    border-radius: 1px;\n"
"}")
        self.option_btn.setObjectName("option_btn")
        self.horizontalLayout_8.addWidget(self.option_btn)
        self.verticalLayout_4.addWidget(self.tab_btn)
        self.menu_stacked_tab = QtWidgets.QStackedWidget(self.menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_stacked_tab.sizePolicy().hasHeightForWidth())
        self.menu_stacked_tab.setSizePolicy(sizePolicy)
        self.menu_stacked_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_stacked_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_stacked_tab.setStyleSheet("background-color: #f0edee;")
        self.menu_stacked_tab.setObjectName("menu_stacked_tab")
        self.path_page = QtWidgets.QWidget()
        self.path_page.setStyleSheet("background-color: rgb(240, 237, 238);")
        self.path_page.setObjectName("path_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.path_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.path_sect_storage = QtWidgets.QFrame(self.path_page)
        self.path_sect_storage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.path_sect_storage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.path_sect_storage.setObjectName("path_sect_storage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.path_sect_storage)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.path_status = QtWidgets.QFrame(self.path_sect_storage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_status.sizePolicy().hasHeightForWidth())
        self.path_status.setSizePolicy(sizePolicy)
        self.path_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.path_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.path_status.setObjectName("path_status")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.path_status)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.path_name = QtWidgets.QLabel(self.path_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_name.sizePolicy().hasHeightForWidth())
        self.path_name.setSizePolicy(sizePolicy)
        self.path_name.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 20pt \"Moon\";\n"
"font-weight:bold;")
        self.path_name.setObjectName("path_name")
        self.horizontalLayout_9.addWidget(self.path_name)
        self.verticalLayout_7.addWidget(self.path_status)
        self.parameter_frame = QtWidgets.QFrame(self.path_sect_storage)
        self.parameter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.parameter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameter_frame.setObjectName("parameter_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.parameter_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.parameter_frame)
        self.label_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.speed_sect = QtWidgets.QFrame(self.parameter_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_sect.sizePolicy().hasHeightForWidth())
        self.speed_sect.setSizePolicy(sizePolicy)
        self.speed_sect.setMaximumSize(QtCore.QSize(16777215, 360))
        self.speed_sect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.speed_sect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speed_sect.setObjectName("speed_sect")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.speed_sect)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speed_label = QtWidgets.QLabel(self.speed_sect)
        self.speed_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.speed_label.setObjectName("speed_label")
        self.gridLayout_2.addWidget(self.speed_label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.speed_input = QtWidgets.QLineEdit(self.speed_sect)
        self.speed_input.setValidator(QDoubleValidator())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_input.sizePolicy().hasHeightForWidth())
        self.speed_input.setSizePolicy(sizePolicy)
        self.speed_input.setMinimumSize(QtCore.QSize(0, 0))
        self.speed_input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.speed_input.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;\n"
"background-color:rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 5px;")
        self.speed_input.setObjectName("speed_input")
        self.gridLayout_2.addWidget(self.speed_input, 0, 1, 1, 1)
        self.speed_unit = QtWidgets.QLabel(self.speed_sect)
        self.speed_unit.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.speed_unit.setObjectName("speed_unit")
        self.gridLayout_2.addWidget(self.speed_unit, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.speed_sect)
        self.label_2.setStyleSheet("color:#EC0B43;\n"
"font: 75 8pt \"Moon\";\n"
"font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.speed_sect)
        self.angle_sect = QtWidgets.QFrame(self.parameter_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_sect.sizePolicy().hasHeightForWidth())
        self.angle_sect.setSizePolicy(sizePolicy)
        self.angle_sect.setMaximumSize(QtCore.QSize(16777215, 360))
        self.angle_sect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.angle_sect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.angle_sect.setObjectName("angle_sect")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.angle_sect)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.angle_label = QtWidgets.QLabel(self.angle_sect)
        self.angle_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.angle_label.setObjectName("angle_label")
        self.gridLayout_3.addWidget(self.angle_label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.angle_input = QtWidgets.QLineEdit(self.angle_sect)
        self.angle_input.setValidator(QDoubleValidator())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_input.sizePolicy().hasHeightForWidth())
        self.angle_input.setSizePolicy(sizePolicy)
        self.angle_input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.angle_input.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;\n"
"background-color:rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 5px;")
        self.angle_input.setObjectName("angle_input")
        self.gridLayout_3.addWidget(self.angle_input, 0, 1, 1, 1)
        self.angle_unit = QtWidgets.QLabel(self.angle_sect)
        self.angle_unit.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.angle_unit.setObjectName("angle_unit")
        self.gridLayout_3.addWidget(self.angle_unit, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.angle_sect)
        self.label_3.setStyleSheet("color:#EC0B43;\n"
"font: 75 8pt \"Moon\";\n"
"font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 3, QtCore.Qt.AlignLeft)
        self.verticalLayout_5.addWidget(self.angle_sect)
        self.verticalLayout_7.addWidget(self.parameter_frame)
        self.calculated_frame = QtWidgets.QFrame(self.path_sect_storage)
        self.calculated_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calculated_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calculated_frame.setObjectName("calculated_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.calculated_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.calculated_label = QtWidgets.QLabel(self.calculated_frame)
        self.calculated_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.calculated_label.setObjectName("calculated_label")
        self.verticalLayout_6.addWidget(self.calculated_label)
        self.time_used_option = QtWidgets.QFrame(self.calculated_frame)
        self.time_used_option.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.time_used_option.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_used_option.setObjectName("time_used_option")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.time_used_option)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.time_used_label = QtWidgets.QLabel(self.time_used_option)
        self.time_used_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.time_used_label.setObjectName("time_used_label")
        self.horizontalLayout_12.addWidget(self.time_used_label, 0, QtCore.Qt.AlignLeft)
        self.time_used_display = QtWidgets.QLabel(self.time_used_option)
        self.time_used_display.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.time_used_display.setObjectName("time_used_display")
        self.horizontalLayout_12.addWidget(self.time_used_display, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.time_used_option)
        self.u_x_option = QtWidgets.QFrame(self.calculated_frame)
        self.u_x_option.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.u_x_option.setFrameShadow(QtWidgets.QFrame.Raised)
        self.u_x_option.setObjectName("u_x_option")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.u_x_option)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.u_x_label = QtWidgets.QLabel(self.u_x_option)
        self.u_x_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.u_x_label.setObjectName("u_x_label")
        self.horizontalLayout_13.addWidget(self.u_x_label, 0, QtCore.Qt.AlignLeft)
        self.s_x_display = QtWidgets.QLabel(self.u_x_option)
        self.s_x_display.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.s_x_display.setObjectName("s_x_display")
        self.horizontalLayout_13.addWidget(self.s_x_display, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.u_x_option)
        self.u_y_option = QtWidgets.QFrame(self.calculated_frame)
        self.u_y_option.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.u_y_option.setFrameShadow(QtWidgets.QFrame.Raised)
        self.u_y_option.setObjectName("u_y_option")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.u_y_option)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.u_y_label = QtWidgets.QLabel(self.u_y_option)
        self.u_y_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.u_y_label.setObjectName("u_y_label")
        self.horizontalLayout_14.addWidget(self.u_y_label, 0, QtCore.Qt.AlignLeft)
        self.s_y_display = QtWidgets.QLabel(self.u_y_option)
        self.s_y_display.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.s_y_display.setObjectName("s_y_display")
        self.horizontalLayout_14.addWidget(self.s_y_display, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.u_y_option)
        self.verticalLayout_7.addWidget(self.calculated_frame)
        self.verticalLayout_11.addWidget(self.path_sect_storage)
        self.menu_stacked_tab.addWidget(self.path_page)
        self.option_page = QtWidgets.QWidget()
        self.option_page.setObjectName("option_page")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.option_page)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.option_sect_storage = QtWidgets.QFrame(self.option_page)
        self.option_sect_storage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.option_sect_storage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.option_sect_storage.setObjectName("option_sect_storage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.option_sect_storage)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.env_option_sect = QtWidgets.QFrame(self.option_sect_storage)
        self.env_option_sect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.env_option_sect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.env_option_sect.setObjectName("env_option_sect")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.env_option_sect)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.env_option_label = QtWidgets.QLabel(self.env_option_sect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_option_label.sizePolicy().hasHeightForWidth())
        self.env_option_label.setSizePolicy(sizePolicy)
        self.env_option_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.env_option_label.setObjectName("env_option_label")
        self.verticalLayout_9.addWidget(self.env_option_label)
        self.env_choice = QtWidgets.QFrame(self.env_option_sect)
        self.env_choice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.env_choice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.env_choice.setObjectName("env_choice")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.env_choice)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.show_cont_checkbox = QtWidgets.QCheckBox(self.env_choice)
        self.show_cont_checkbox.setStyleSheet("QCheckBox{\n"
"color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Moon\";\n"
"font-weight:bold;\n"
"border: 2px solid #999999;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}")
        self.show_cont_checkbox.setObjectName("show_cont_checkbox")
        self.verticalLayout_8.addWidget(self.show_cont_checkbox)
        self.verticalLayout_9.addWidget(self.env_choice)
        self.verticalLayout_13.addWidget(self.env_option_sect)
        self.save_option_sect = QtWidgets.QFrame(self.option_sect_storage)
        self.save_option_sect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_option_sect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_option_sect.setObjectName("save_option_sect")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.save_option_sect)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.save_option_label = QtWidgets.QLabel(self.save_option_sect)
        self.save_option_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.save_option_label.setObjectName("save_option_label")
        self.verticalLayout_12.addWidget(self.save_option_label)
        self.save_option_choice = QtWidgets.QFrame(self.save_option_sect)
        self.save_option_choice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_option_choice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_option_choice.setObjectName("save_option_choice")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.save_option_choice)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.save_setting = QtWidgets.QFrame(self.save_option_choice)
        self.save_setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_setting.setObjectName("save_setting")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.save_setting)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.save_file_as_label = QtWidgets.QLabel(self.save_setting)
        self.save_file_as_label.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Moon\";\n"
"font-weight:bold;")
        self.save_file_as_label.setObjectName("save_file_as_label")
        self.horizontalLayout_15.addWidget(self.save_file_as_label, 0, QtCore.Qt.AlignLeft)
        self.file_type_select = QtWidgets.QComboBox(self.save_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_type_select.sizePolicy().hasHeightForWidth())
        self.file_type_select.setSizePolicy(sizePolicy)
        self.file_type_select.setMaximumSize(QtCore.QSize(100, 16777215))
        self.file_type_select.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Moon\";\n"
"font-weight:bold;")
        self.file_type_select.setObjectName("file_type_select")
        self.file_type_select.addItem("")
        self.file_type_select.addItem("")
        self.horizontalLayout_15.addWidget(self.file_type_select, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_10.addWidget(self.save_setting)
        self.save_calc_btn = QtWidgets.QPushButton(self.save_option_choice)
        self.save_calc_btn.setStyleSheet("QPushButton{\n"
"    color: #ffd400;\n"
"    font: 75 12pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#000000;\n"
"    padding: 8px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton::Pressed{\n"
"    color: #fff106;\n"
"    font: 75 12pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#000000;\n"
"    padding: 8px;\n"
"    border-radius: 18px;\n"
"}")
        self.save_calc_btn.setObjectName("save_calc_btn")
        self.verticalLayout_10.addWidget(self.save_calc_btn)
        self.verticalLayout_12.addWidget(self.save_option_choice)
        self.verticalLayout_13.addWidget(self.save_option_sect)
        self.verticalLayout_14.addWidget(self.option_sect_storage)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self.menu_stacked_tab.addWidget(self.option_page)
        self.verticalLayout_4.addWidget(self.menu_stacked_tab)
        spacerItem1 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.error_stacked_tab = QtWidgets.QStackedWidget(self.menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.error_stacked_tab.sizePolicy().hasHeightForWidth())
        self.error_stacked_tab.setSizePolicy(sizePolicy)
        self.error_stacked_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.error_stacked_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.error_stacked_tab.setStyleSheet("background-color: #f0edee;")
        self.error_stacked_tab.setObjectName("error_stacked_tab")
        self.err_0 = QtWidgets.QWidget()
        self.err_0.setObjectName("err_0")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.err_0)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.noti_label_0 = QtWidgets.QLabel(self.err_0)
        self.noti_label_0.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.noti_label_0.setObjectName("noti_label_0")
        self.verticalLayout_15.addWidget(self.noti_label_0)
        spacerItem2 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem2)
        self.noti_err_0 = QtWidgets.QLabel(self.err_0)
        self.noti_err_0.setStyleSheet("color:#337357;\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.noti_err_0.setObjectName("noti_err_0")
        self.verticalLayout_15.addWidget(self.noti_err_0)
        spacerItem3 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_15.addItem(spacerItem3)
        self.error_stacked_tab.addWidget(self.err_0)
        self.err_1 = QtWidgets.QWidget()
        self.err_1.setObjectName("err_1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.err_1)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.noti_label_1 = QtWidgets.QLabel(self.err_1)
        self.noti_label_1.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.noti_label_1.setObjectName("noti_label_1")
        self.verticalLayout_16.addWidget(self.noti_label_1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem4)
        self.noti_error_1 = QtWidgets.QLabel(self.err_1)
        self.noti_error_1.setStyleSheet("color:#EC0B43;\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.noti_error_1.setObjectName("noti_error_1")
        self.verticalLayout_16.addWidget(self.noti_error_1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem5)
        self.error_stacked_tab.addWidget(self.err_1)
        self.err_2 = QtWidgets.QWidget()
        self.err_2.setObjectName("err_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.err_2)
        self.verticalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.noti_label_2 = QtWidgets.QLabel(self.err_2)
        self.noti_label_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.noti_label_2.setObjectName("noti_label_2")
        self.verticalLayout_17.addWidget(self.noti_label_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem6)
        self.noti_err_2 = QtWidgets.QLabel(self.err_2)
        self.noti_err_2.setStyleSheet("color:#EC0B43;\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.noti_err_2.setObjectName("noti_err_2")
        self.verticalLayout_17.addWidget(self.noti_err_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem7)
        self.error_stacked_tab.addWidget(self.err_2)
        self.err_3 = QtWidgets.QWidget()
        self.err_3.setObjectName("err_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.err_3)
        self.verticalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.noti_label_3 = QtWidgets.QLabel(self.err_3)
        self.noti_label_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"border-bottom:2.5px solid #999999;")
        self.noti_label_3.setObjectName("noti_label_3")
        self.verticalLayout_18.addWidget(self.noti_label_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_18.addItem(spacerItem8)
        self.noti_err_3 = QtWidgets.QLabel(self.err_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noti_err_3.sizePolicy().hasHeightForWidth())
        self.noti_err_3.setSizePolicy(sizePolicy)
        self.noti_err_3.setStyleSheet("color:#EC0B43;\n"
"font: 75 14pt \"Moon\";\n"
"font-weight:bold;")
        self.noti_err_3.setObjectName("noti_err_3")
        self.verticalLayout_18.addWidget(self.noti_err_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_18.addItem(spacerItem9)
        self.error_stacked_tab.addWidget(self.err_3)
        self.verticalLayout_4.addWidget(self.error_stacked_tab, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.menu_frame)
        self.Start_frame = QtWidgets.QFrame(self.Panel_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_frame.sizePolicy().hasHeightForWidth())
        self.Start_frame.setSizePolicy(sizePolicy)
        self.Start_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Start_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Start_frame.setObjectName("Start_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Start_frame)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_btn = QtWidgets.QPushButton(self.Start_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setStyleSheet("QPushButton{\n"
"    color: #ffd400;\n"
"    font: 75 15pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#000000;\n"
"    padding: 8px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton::Pressed{\n"
"    color: #fff106;\n"
"    font: 75 15pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#000000;\n"
"    padding: 8px;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QPushButton::disabled{\n"
"    color: #c1cfda;\n"
"    font: 75 15pt \"Moon\";\n"
"    font-weight:bold;\n"
"    background-color:#000000;\n"
"    padding: 8px;\n"
"    border-radius: 18px;\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_3.addWidget(self.start_btn)
        self.verticalLayout.addWidget(self.Start_frame)
        self.horizontalLayout.addWidget(self.Panel_frame)
        self.Display_Frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Frame.sizePolicy().hasHeightForWidth())
        self.Display_Frame.setSizePolicy(sizePolicy)
        self.Display_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Display_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Display_Frame.setObjectName("Display_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Display_Frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Graph_widget = PlotWidget(self.Display_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Graph_widget.sizePolicy().hasHeightForWidth())
        self.Graph_widget.setSizePolicy(sizePolicy)
        self.Graph_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.Graph_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Graph_widget.setObjectName("Graph_widget")
        self.verticalLayout_2.addWidget(self.Graph_widget)
        self.Control_frame = QtWidgets.QFrame(self.Display_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Control_frame.sizePolicy().hasHeightForWidth())
        self.Control_frame.setSizePolicy(sizePolicy)
        self.Control_frame.setStyleSheet("background-color: rgb(240, 237, 238);")
        self.Control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Control_frame.setObjectName("Control_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Control_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Target_parameter = QtWidgets.QFrame(self.Control_frame)
        self.Target_parameter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_parameter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_parameter.setObjectName("Target_parameter")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Target_parameter)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pos_header_parameter = QtWidgets.QFrame(self.Target_parameter)
        self.pos_header_parameter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pos_header_parameter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pos_header_parameter.setObjectName("pos_header_parameter")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.pos_header_parameter)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.target_position = QtWidgets.QLabel(self.pos_header_parameter)
        self.target_position.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;")
        self.target_position.setObjectName("target_position")
        self.horizontalLayout_7.addWidget(self.target_position, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.pos_header_parameter, 0, QtCore.Qt.AlignLeft)
        self.pos_x_parameter = QtWidgets.QFrame(self.Target_parameter)
        self.pos_x_parameter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pos_x_parameter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pos_x_parameter.setObjectName("pos_x_parameter")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.pos_x_parameter)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.x_equal = QtWidgets.QLabel(self.pos_x_parameter)
        self.x_equal.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;")
        self.x_equal.setObjectName("x_equal")
        self.horizontalLayout_6.addWidget(self.x_equal, 0, QtCore.Qt.AlignLeft)
        self.pos_x_input = QtWidgets.QLineEdit(self.pos_x_parameter)
        self.pos_x_input.setValidator(QDoubleValidator())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_x_input.sizePolicy().hasHeightForWidth())
        self.pos_x_input.setSizePolicy(sizePolicy)
        self.pos_x_input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pos_x_input.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;\n"
"background-color:rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 5px;")
        self.pos_x_input.setText("")
        self.pos_x_input.setObjectName("pos_x_input")
        self.horizontalLayout_6.addWidget(self.pos_x_input, 0, QtCore.Qt.AlignLeft)
        self.x_unit = QtWidgets.QLabel(self.pos_x_parameter)
        self.x_unit.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;")
        self.x_unit.setObjectName("x_unit")
        self.horizontalLayout_6.addWidget(self.x_unit, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.pos_x_parameter, 0, QtCore.Qt.AlignLeft)
        self.pos_y_parameter = QtWidgets.QFrame(self.Target_parameter)
        self.pos_y_parameter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pos_y_parameter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pos_y_parameter.setObjectName("pos_y_parameter")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.pos_y_parameter)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.y_unit = QtWidgets.QLabel(self.pos_y_parameter)
        self.y_unit.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;")
        self.y_unit.setObjectName("y_unit")
        self.horizontalLayout_5.addWidget(self.y_unit, 0, QtCore.Qt.AlignLeft)
        self.pos_y_input = QtWidgets.QLineEdit(self.pos_y_parameter)
        self.pos_y_input.setValidator(QDoubleValidator())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_y_input.sizePolicy().hasHeightForWidth())
        self.pos_y_input.setSizePolicy(sizePolicy)
        self.pos_y_input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pos_y_input.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;\n"
"background-color:rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius: 5px;")
        self.pos_y_input.setObjectName("pos_y_input")
        self.horizontalLayout_5.addWidget(self.pos_y_input, 0, QtCore.Qt.AlignLeft)
        self.label_7 = QtWidgets.QLabel(self.pos_y_parameter)
        self.label_7.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Moon\";\n"
"font-weight:bold;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.pos_y_parameter, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.Target_parameter, 0, QtCore.Qt.AlignLeft)
        self.button_frame = QtWidgets.QFrame(self.Control_frame)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout_4.setContentsMargins(18, -1, 18, 11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.play_pause_btn = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_pause_btn.sizePolicy().hasHeightForWidth())
        self.play_pause_btn.setSizePolicy(sizePolicy)
        self.play_pause_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.play_pause_btn.setMaximumSize(QtCore.QSize(10, 16777215))
        self.play_pause_btn.setStyleSheet("color: rgb(240, 237, 238);\n"
"font: 75 15pt \"Moon\";\n"
"font-weight:bold;\n"
"background-color: rgb(240, 237, 238);\n"
"padding: 4px;\n"
"border: 3px solid rgb(240, 237, 238);\n"
"border-radius: 6px;")
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.horizontalLayout_4.addWidget(self.play_pause_btn, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.button_frame)
        self.label.setStyleSheet("color:#EC0B43;\n"
"font: 75 12pt \"Moon\";\n"
"font-weight:bold;")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.button_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.Control_frame)
        self.horizontalLayout.addWidget(self.Display_Frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu_stacked_tab.setCurrentIndex(0)
        self.error_stacked_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.percent_label.setText(_translate("MainWindow", "0.00%"))
        self.progress_label.setText(_translate("MainWindow", "Progress               "))
        self.path_btn.setText(_translate("MainWindow", "Path"))
        self.option_btn.setText(_translate("MainWindow", "Option"))
        self.path_name.setText(_translate("MainWindow", "Path 1"))
        self.label_5.setText(_translate("MainWindow", "Parameters"))
        self.speed_label.setText(_translate("MainWindow", "speed"))
        self.speed_unit.setText(_translate("MainWindow", "m/s"))
        self.label_2.setText(_translate("MainWindow", "must be positive number"))
        self.angle_label.setText(_translate("MainWindow", "angle"))
        self.angle_unit.setText(_translate("MainWindow", "degree"))
        self.label_3.setText(_translate("MainWindow", "must be between 0 to 90 degree"))
        self.calculated_label.setText(_translate("MainWindow", "Calculated Variable"))
        self.time_used_label.setText(_translate("MainWindow", "Time used: "))
        self.time_used_display.setText(_translate("MainWindow", "n/a sec"))
        self.u_x_label.setText(_translate("MainWindow", "s_x: "))
        self.s_x_display.setText(_translate("MainWindow", "0 meter"))
        self.u_y_label.setText(_translate("MainWindow", "s_y: "))
        self.s_y_display.setText(_translate("MainWindow", "0.4 meter"))
        self.env_option_label.setText(_translate("MainWindow", "Environment Option"))
        self.show_cont_checkbox.setText(_translate("MainWindow", "Show Mark Timestamp"))
        self.save_option_label.setText(_translate("MainWindow", "File Save Option"))
        self.save_file_as_label.setText(_translate("MainWindow", "Save File as"))
        self.file_type_select.setItemText(0, _translate("MainWindow", "CSV"))
        self.file_type_select.setItemText(1, _translate("MainWindow", "TXT"))
        self.save_calc_btn.setText(_translate("MainWindow", "Save Calculation"))
        self.noti_label_0.setText(_translate("MainWindow", "Notification"))
        self.noti_err_0.setText(_translate("MainWindow", "Passed: Valid Parameters"))
        self.noti_label_1.setText(_translate("MainWindow", "Notification"))
        self.noti_error_1.setText(_translate("MainWindow", "Err 1: invalid speed input"))
        self.noti_label_2.setText(_translate("MainWindow", "Notification"))
        self.noti_err_2.setText(_translate("MainWindow", "Err 2: Invalid Angle Input"))
        self.noti_label_3.setText(_translate("MainWindow", "Notification"))
        self.noti_err_3.setText(_translate("MainWindow", "Err 3: Invalid target pos"))
        self.start_btn.setText(_translate("MainWindow", "start route"))
        self.target_position.setText(_translate("MainWindow", "  Target Position:  "))
        self.x_equal.setText(_translate("MainWindow", "X ="))
        self.x_unit.setText(_translate("MainWindow", "Meter,   "))
        self.y_unit.setText(_translate("MainWindow", "Y = "))
        self.label_7.setText(_translate("MainWindow", "Meter"))
        self.play_pause_btn.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", "target input must be positive number"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
